services:
  db:
    image: postgres:${POSTGRES_VERSION}
    container_name: ${POSTGRES_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /var/lib/postgresql/data/pgdata
      TZ: ${TZ}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - odoo19-postgres-data:/var/lib/postgresql/data/pgdata
    networks:
      - odoo19-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  mailpit:
    image: axllent/mailpit:latest
    container_name: ${MAILPIT_CONTAINER_NAME}
    restart: unless-stopped
    environment:
      TZ: ${TZ}
    ports:
      - "${MAILPIT_SMTP_PORT}:1025"
      - "${MAILPIT_WEB_PORT}:8025"
    networks:
      - odoo19-net

volumes:
  odoo19-postgres-data:
    name: odoo19-postgres-data

networks:
  odoo19-net:
    name: odoo19-net
    driver: bridge