[options]
admin_passwd = admin

db_host = localhost
db_port = 5432
db_user = odoo
db_password = odoo

addons_path =
    /home/ruiznorlan/Documentos/odoo/19.0/odoo/addons,
    /home/ruiznorlan/Documentos/odoo/19.0/addons,
    /home/ruiznorlan/Documentos/odoo_dev_env/addons/custom,
    /home/ruiznorlan/Documentos/odoo_dev_env/addons/third_party

data_dir = /home/ruiznorlan/Documentos/odoo_dev_env/.local/share/Odoo19

http_port = 8069
workers = 0
max_cron_threads = 1
dev = all
log_level = info

smtp_server = localhost
smtp_port = 1025
smtp_ssl = False
smtp_user = False
smtp_password = False

limit_time_cpu = 600
limit_time_real = 1200
limit_memory_soft = 2147483648
limit_memory_hard = 2684354560